# Generated by Django 3.0.7 on 2020-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200804_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='sex',
            field=models.CharField(choices=[('mail', 'Мужской'), ('femail', 'Женский'), ('other', 'Не указан')], default='other', max_length=6, verbose_name='Пол'),
        ),
    ]
